"I can't join to the voice channel": {"I can't join to the channel"};
"You need to join a voice channel": {"You need to join a voice channel"};
"The video is copyrighted": {"The video is copyrighted"};
"added to the queue": {"added to the queue"};
"I don't playing music right now": {"I don't playing music right now"};
"Playing:": {"Playing"};
"Ping": {"Ping"};
"Do you know the synonyms?": {"Do you know the synonyms?"};
"You don't have permission to do that": {"You don't have permission to do that"};
"created": {"created"};
"I can't send this to a not NSFW channel.": {"I can't send this to a not NSFW channel."};
"The badwords filter is now on": {"The badwords filter is now on"};
"The badwords filter is now off": {"The badwords filter is now off"};
"Already set to this setting.": {"Already set to this setting."};
"This command does not exist!": {"This command does not exist!"};
"Great. You set this setting": {"Great. You set this setting"};
